//
// Created by suz305 on 2/27/19.
//

#ifndef STATIC_WP_LAVA_WPEXPR_H
#define STATIC_WP_LAVA_WPEXPR_H

#include <memory>
#include "llvm/IR/Value.h"
#include "llvm/Support/raw_ostream.h"
#include "z3++.h"
#include <list>

namespace WpExpr{
    enum NodeType {
        BINOP,        //Binary Operator
        UNIOP,        //Unary Operator
        VAR,          //Variable
        CONST,        //Constant
        UPRED         //Undetermined predicate of a variable
    };
    enum Operator {PLUS, MINUS, AND, OR, MUL, DIV, IND, MOD, XOR,//binop
            TO_INT, TO_REAL, NOT, //Uniop
            GT, GE, EQ, NEQ, LT, LE //Compare
    };

    static const char *wp_init_var = "__wp_init_var";

    class Node : public std::enable_shared_from_this<Node> {
    public:
        NodeType type;
        Operator operatorType;
        std::shared_ptr<Node> left, right;
        llvm::Value *valueObj;
        std::string value;
        std::string &name;

        Node() : name(value),valueObj(nullptr) {}

        Node(Node &node);

        Node(NodeType type, std::shared_ptr<Node> &&left, std::shared_ptr<Node> &&right, std::string &&val) :
                type(type), left(std::move(left)), right(std::move(right)), value(std::move(val)), name(value) {

        }

        std::string GetName();
        std::string ToString();

        std::string ToSMTLanguage();

        static std::shared_ptr<Node> CreateBinOp(std::shared_ptr<Node> &&left, std::shared_ptr<Node> &&right, Operator optr);

        static std::shared_ptr<Node> CreateUniOp(std::shared_ptr<Node> &&left, Operator optr);

        static std::shared_ptr<Node> CreateVar(llvm::Value *val);

        static std::shared_ptr<Node> CreateVar(std::string name);

        static std::shared_ptr<Node> CreateConst(std::string value);

        static std::shared_ptr<Node> CreateUndeterminedPredicate(llvm::Value *val);

        /**
         * This function fills the undetermined predicates generated by a function call.
         * @param upred The expression containing the undetermined predicate.
         * @param expr The expression to be filled. Usually it is the WP.
         * @param retValName The name of the call instrution. It should be in expr.
         * @return Returns the upred.
         */
        static void fillUndeterminedPredicate(std::shared_ptr<Node> &upred, const std::shared_ptr<Node> &expr, const llvm::Value *val);
        static void fillUndeterminedPredicate(std::list<std::shared_ptr<Node> > &upred, const std::shared_ptr<Node> &expr, const llvm::Value *val);

        static std::shared_ptr<Node> substitute(std::shared_ptr<Node> &src, const llvm::Value *val, const std::shared_ptr<Node> &expr);
        static std::list<std::shared_ptr<Node> > &
        substitute(std::list<std::shared_ptr<Node> > &src, const llvm::Value *val, const std::shared_ptr<Node> &expr);

        static void fillUndeterminedPredicate(std::list<std::shared_ptr<Node>> &upred, const std::list<std::shared_ptr<Node>> &expr_list,
                                   const llvm::Value *val);
    };

    static z3::context defaultcontext;
    typedef std::shared_ptr<WpExpr::Node> NodePtr;
    //static NodePtr substitute(NodePtr &src, const llvm::Value *val, const NodePtr &expr);



}




#endif //STATIC_WP_LAVA_WPEXPR_H
